/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author basirudin
 */
public class view_pilihanPaket extends javax.swing.JFrame {

    /**
     * Creates new form view_pilihanPaket
     */
    public view_pilihanPaket() {
        initComponents();
    }

    public void btnPaketListener(ActionListener e) {
        this.btn_paket.addActionListener(e);
    }

    public void btnPaket3jamListener(ActionListener e) {
        this.btn_paket3jam.addActionListener(e);
    }

    public void btnPaket5JamListener(ActionListener e) {
        this.btn_paket5jam.addActionListener(e);
    }

    public JTextField setPaket() {
        return tf_paket;
    }

    public JTextField setPaket3Jam() {
        return tf_paket3jam;
    }

    public JTextField setPaket5Jam() {
        return tf_paket5jam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_paket = new javax.swing.JTextField();
        tf_paket3jam = new javax.swing.JTextField();
        tf_paket5jam = new javax.swing.JTextField();
        btn_paket = new javax.swing.JButton();
        btn_paket3jam = new javax.swing.JButton();
        btn_paket5jam = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PILIHAN PAKET WARNET");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_paket.setEditable(false);
        tf_paket.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_paket.setText("-");
        tf_paket.setBorder(null);
        tf_paket.setOpaque(false);
        getContentPane().add(tf_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 40));

        tf_paket3jam.setEditable(false);
        tf_paket3jam.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_paket3jam.setText("-");
        tf_paket3jam.setBorder(null);
        tf_paket3jam.setOpaque(false);
        getContentPane().add(tf_paket3jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 40));

        tf_paket5jam.setEditable(false);
        tf_paket5jam.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_paket5jam.setText("-");
        tf_paket5jam.setBorder(null);
        tf_paket5jam.setOpaque(false);
        getContentPane().add(tf_paket5jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, 40));

        btn_paket.setBorder(null);
        btn_paket.setContentAreaFilled(false);
        btn_paket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_paket.setFocusable(false);
        getContentPane().add(btn_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        btn_paket3jam.setBorder(null);
        btn_paket3jam.setContentAreaFilled(false);
        btn_paket3jam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_paket3jam.setFocusable(false);
        getContentPane().add(btn_paket3jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 40));

        btn_paket5jam.setBorder(null);
        btn_paket5jam.setContentAreaFilled(false);
        btn_paket5jam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_paket5jam.setFocusable(false);
        getContentPane().add(btn_paket5jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pilihan paket.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_pilihanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_pilihanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_pilihanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_pilihanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_pilihanPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_paket;
    private javax.swing.JButton btn_paket3jam;
    private javax.swing.JButton btn_paket5jam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_paket;
    private javax.swing.JTextField tf_paket3jam;
    private javax.swing.JTextField tf_paket5jam;
    // End of variables declaration//GEN-END:variables
}
