/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author basirudin
 */
public class view_pengguna extends javax.swing.JFrame {

    /**
     * Creates new form view_pengguna
     */
    public view_pengguna() {
        initComponents();
    }

    public void btnStopListener(ActionListener e) {
        this.btn_stop.addActionListener(e);
    }

    public JButton getStop() {
        return btn_stop;
    }

    public JTextField getID() {
        return tf_ID;
    }

    public JTextField setUsername() {
        return tf_username;
    }

    public JTextField setJam() {
        return tf_jam;
    }

    public JTextField setMenit() {
        return tf_menit;
    }

    public JTextField setDetik() {
        return tf_detik;
    }

    public JTextField setBiaya() {
        return tf_biaya;
    }

    public JTextField setKomputer() {
        return tf_komputer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_jam = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        tf_komputer = new javax.swing.JTextField();
        tf_biaya = new javax.swing.JTextField();
        btn_stop = new javax.swing.JButton();
        tf_menit = new javax.swing.JTextField();
        tf_detik = new javax.swing.JTextField();
        tf_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAKET/JAM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_jam.setEditable(false);
        tf_jam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_jam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_jam.setText("0");
        tf_jam.setBorder(null);
        tf_jam.setFocusable(false);
        tf_jam.setOpaque(false);
        getContentPane().add(tf_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 92, 15, 20));

        tf_username.setEditable(false);
        tf_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_username.setText("-");
        tf_username.setBorder(null);
        tf_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_username.setOpaque(false);
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 55, 180, 20));

        tf_komputer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_komputer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_komputer.setText("-");
        tf_komputer.setBorder(null);
        tf_komputer.setFocusable(false);
        tf_komputer.setOpaque(false);
        getContentPane().add(tf_komputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 165, 140, 20));

        tf_biaya.setEditable(false);
        tf_biaya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_biaya.setText("0");
        tf_biaya.setBorder(null);
        tf_biaya.setFocusable(false);
        tf_biaya.setOpaque(false);
        getContentPane().add(tf_biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 130, 80, 20));

        btn_stop.setBorder(null);
        btn_stop.setContentAreaFilled(false);
        btn_stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 50, 100, 140));

        tf_menit.setEditable(false);
        tf_menit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_menit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_menit.setText("0");
        tf_menit.setBorder(null);
        tf_menit.setFocusable(false);
        tf_menit.setOpaque(false);
        getContentPane().add(tf_menit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 92, 20, 20));

        tf_detik.setEditable(false);
        tf_detik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_detik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_detik.setText("0");
        tf_detik.setBorder(null);
        tf_detik.setOpaque(false);
        getContentPane().add(tf_detik, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 92, 20, 20));

        tf_ID.setEditable(false);
        tf_ID.setBorder(null);
        tf_ID.setOpaque(false);
        getContentPane().add(tf_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pengguna.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_ID;
    private javax.swing.JTextField tf_biaya;
    private javax.swing.JTextField tf_detik;
    private javax.swing.JTextField tf_jam;
    private javax.swing.JTextField tf_komputer;
    private javax.swing.JTextField tf_menit;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
